-- CREACIÓN DE TABLAS
CREATE TABLE CLIENTES_A (
    ID_CLIENTE NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(50),
    CIUDAD VARCHAR2(40)
);

CREATE TABLE PRODUCTOS_S (
    ID_PRODUCTO NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(50),
    PRECIO NUMBER(10,2)
);

-- 40 REGISTROS CLIENTES
BEGIN
  FOR i IN 1..40 LOOP
    INSERT INTO CLIENTES_A VALUES(i, 'Cliente '||i, 'Ciudad '||MOD(i,5));
  END LOOP;
  COMMIT;
END;
/

-- 80 REGISTROS PRODUCTOS
BEGIN
  FOR i IN 1..80 LOOP
    INSERT INTO PRODUCTOS_S VALUES(i, 'Producto '||i, (i*1000));
  END LOOP;
  COMMIT;
END;
/   
COMMIT;